# Generated by Django 4.2.4 on 2023-08-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('credit_card', 'Credit Card')], default='cod', max_length=20),
        ),
    ]
