# Generated by Django 4.2.4 on 2023-08-19 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
    ]
